name: Flutter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Flutter with explicit version
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'  # Replace with the latest version if needed

      # Upgrade Flutter (Optional)
      - name: Upgrade Flutter
        run: flutter upgrade

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Verify formatting (optional)
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Analyze project source code
      - name: Analyze project source
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test
